title: Steven Osantowski # your name (or website title) here
logo: "images/Screenshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Steve is currently studying for an Associate Degree of Applied Science in IT- Web and Software Development.  
  <br><br>
  Second description 
  <br><br>
  Thrid description 
  <br><br>
  <a href="https://www.linkedin.com/in/steve-osantowski-8b5b24b0/">View My LinkedIn Profile</a> 
  
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
