title: Steven Osantowski # your name (or website title) here
logo: "images/Picture2.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br><br>
 Hello, my name is Steven Osantowski. I am currently pursuing my Associates in IT-Web and Software Developer at WCTC.  I expect to graduate May of 2022 and currently have a 4.0 GPA.
 <br><br>
 I am excited by the opportunity to gain experience where I can use my technology adoption and implementation experience to write code with the end-user in mind.
 <br><br>
  <a href="https://www.linkedin.com/in/steve-osantowski-8b5b24b0/">View My LinkedIn Profile</a> 
  
 





theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here